version: 0.2

phases:
  install:
    commands:
      - echo Installing packages...
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp s3://nhts3/myarchive.zip .
  post_build:
    commands:
      - echo Build completed on `date`
