version: 0.2

phases:
  install:
    commands:
      - echo Installing packages...
  build:
    commands:
      - echo Build started on `date`
      - curl -O https://s3.amazonaws.com/nhts3/myarchive.zip
  post_build:
    commands:
      - echo Build completed on `date`
